# Generated by Django 4.2.4 on 2023-08-21 13:53

import autoslug.fields
import book_management.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=250, populate_from=book_management.utils.instance_field, slugify=book_management.utils.slugify_value, unique=True)),
                ('first_name', models.CharField(max_length=70, verbose_name='Имя автора')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия автора')),
                ('country', models.CharField(blank=True, max_length=168, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=250, populate_from=book_management.utils.instance_field, slugify=book_management.utils.slugify_value, unique=True)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=250, populate_from=book_management.utils.instance_field, slugify=book_management.utils.slugify_value, unique=True)),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='Язык книги')),
            ],
            options={
                'verbose_name': 'Язык книги',
                'verbose_name_plural': 'Языки книги',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=250, populate_from=book_management.utils.instance_field, slugify=book_management.utils.slugify_value, unique=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Названия издательства')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес издательства')),
                ('email_address', models.EmailField(blank=True, max_length=250, unique=True, verbose_name='Email адрес')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=250, populate_from=book_management.utils.instance_field, slugify=book_management.utils.slugify_value, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название книги')),
                ('pages', models.IntegerField(default=0, verbose_name='Страницы')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=book_management.utils.path_cover_for_book, verbose_name='Обложка')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(3000)], verbose_name='Год издания')),
                ('show_book', models.BooleanField(default=True, verbose_name='Показать книгу')),
                ('author', models.ManyToManyField(db_index=True, related_name='author', to='book_management.author', verbose_name='Авторы')),
                ('genre', models.ManyToManyField(related_name='genre', to='book_management.genre', verbose_name='Жанр')),
                ('language', models.ManyToManyField(related_name='language', to='book_management.language', verbose_name='Язык книги')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='book_management.publisher', verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
