# Generated by Django 4.2.4 on 2023-08-19 17:25

import book_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=book_management.models.path_cover_for_book, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Жанр'),
        ),
    ]
